critiflix/critiflix/urls.py
from django.urls import include, path
import reviews.views
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', reviews.views.index),
    path('movie-search',reviews.views.movie_search, name='movie_search'),
    path('', include('reviews.urls'))]

 

critiflix/reviews/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    
    path('movies/', views.movie_list, name = 'movie_list'),

   path('movies/<int:pk>', views.movie_detail, name = 'movie_detail'),

   path('', views.base, name = 'base'),

   path('movie_search/', views.movie_search, name='movie_search')
   ]

critiflix/reviews/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class Actor(models.Model):
    first_names = models.CharField(max_length=50, help_text="First name")
    last_names = models.CharField(max_length=50, help_text="Last name")
    birth_dates = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.first_names


class Movie(models.Model):
    movie_name = models.CharField(max_length=50)
    publication_dates = models.DateField(help_text="Publication date of the movie/series", null=True, blank=True)
    duration = models.CharField(max_length=50, default='99', null=True, blank=True)
    film_genre = models.CharField(max_length=50)
    director = models.CharField(max_length=50)
    website = models.URLField(default="http://www.netflix.com/pl/")

    def __str__(self):
        return f"{self.movie_name} - {self.director}"

class MovieCast(models.Model):
    actor = models.ForeignKey(Actor, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    role = models.CharField(max_length=100, help_text="Name of the role")

    def __str__(self):
        return f"{self.actor} as {self.role} in {self.movie}"

class Review(models.Model):
    content = models.TextField(help_text="Review of the movie/series.")
    rating = models.PositiveIntegerField(default=0, help_text="Rating of the movie/series from 1 to 10.", 
                                         validators=[MaxValueValidator(10),MinValueValidator(1)])
    date_created = models.DateTimeField(auto_now_add=True, help_text="Date of writing the review.")
    date_edited = models.DateTimeField(null=True, help_text="Date and time of the last review edit.")
    creator = models.ForeignKey(auth.get_user_model(), on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews', help_text="Reviewed Movie/series.")
    

    def __str__(self):
        return self.creator.username

critiflix/reviews/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(required=False, min_length=3)
    search_in = forms.ChoiceField(required=False,
                                  choices=(
                                      ("movie_name", "Tytuł"),
                                      ("actor", "Aktor")
                                  ))

critiflix/reviews/views.py
from django.shortcuts import render
from .models import Movie, Actor
from .forms import SearchForm
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from .utils import average_rating


def index(request):
    return render(request, "base.html")

def movie_search(request):
    search_text = request.GET.get("search", "")
    form = SearchForm(request.GET)
    movies = set()

    if form.is_valid() and form.cleaned_data["search"]:
        search = form.cleaned_data["search"]
        search_in = form.cleaned_data.get("search_in") or "movie_name"

        if search_in == "movie_name":
            movies = Movie.objects.filter(movie_name__icontains=search)
        else:
            # Szukanie filmów na podstawie aktora
            actor_movies = Movie.objects.filter(
                Q(moviecast__actor__first_names__icontains=search) |
                Q(moviecast__actor__last_names__icontains=search)
            ).distinct()

            movies = actor_movies.prefetch_related('moviecast_set__actor')

    return render(request, "search_results.html", {"form": form, "search_text": search_text, "movies": movies})

def movie_list(request):
    movies = Movie.objects.all()
    movie_list = []

    for movie in movies:
        reviews = movie.reviews.all()

        if reviews:
            movie_rating = average_rating([review.rating for review in reviews])
            number_of_reviews = len(reviews)
        else:
            movie_rating = None
            number_of_reviews = 0

        movie_list.append({'movie': movie, 'movie_rating': movie_rating, 'number_of_reviews': number_of_reviews})

    context = {'movie_list': movie_list}
    return render(request, 'movie_list.html', context)

def movie_detail(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    reviews = movie.reviews.all()

    if reviews:
        movie_rating = average_rating([review.rating for review in reviews])
        context = {'movie': movie, 'movie_rating': movie_rating, 'reviews': reviews}
    else:
        context = {'movie': movie, 'movie_rating': None, 'reviews': None}

    return render(request, 'movie_detail.html', context)

def base(request):
    return render(request, 'base.html')

critiflix/reviews/templates/base.html
{% extends 'base.html' %}
{% load static %}
{% block brand %}<img src="{% static 'reviews/logo.png' %}">{% endblock %}

critiflix/reviews/templates/movie_detail.html
{% extends 'base.html' %}

{% block content %}
        <style>
        .font_h3 {
            font-family: "Noto Sans", sans-serif;
        }

        </style>
        <br>
        <ul>
        <li class="list-group-item">
        <h3 class="text-info font_h3">Szczegółowe informacje o filmie</h3>
        <hr>
        <span class="text-info">Tytuł: </span> <span >{{ movie.movie_name }}</span>
        <br>
        <span class="text-info">Reżyser: </span><span>{{ movie.director }}</span>
        <br>
        <span class="text-info">Data produkcji: </span><span >{{ movie.publication_dates }}</span>
        <br>
        {% if not reviews %}
            <hr>
            <h3 class="text-info">Napisz pierwszą recenzję.</h3>

        {% else %}
                <span class="text-info">Ocena ogólna: </span><span class="badge badge-primary badge-pill">{{ movie_rating }}</span>
                <br>
                 </li>
                <hr>
        </ul>
                <ul>
                        <li class="list-group-item">
                        <h3 class="text-info font_h3">Recenzje:</h3>

                {% for review in reviews %}
                    <li class="list-group-item">
                            <span class="text-info">Recenzja: </span> <span>{{ review.content }}</span>
                            <br>
                            <span class="text-info">Data utworzenia: </span><span>{{ review.date_created }}</span>
                            <br>
                            <span class="text-info">Data edycji: </span><span>{{ review.date_edited }}</span>
                            <br>
                            <span class="text-info">Ocena: </span><span class="badge badge-secondary badge-pill">{{ review.rating }}</span>
                            <br>
                            <span class="text-info">Twórca: </span><span>{{ review.creator.username }}</span>
                            <br>
                    </li>
                {% endfor %}
                </ul>
        {% endif %}
{% endblock %}

critiflix/reviews/templates/movie_list.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-group">
  {% for item in movie_list %}
  <li class="list-group-item">
      <span class="text-info">Tytuł </span> <span>{{ item.movie.movie_name }}</span>
      <br>
      <span class="text-info">Reżyser: </span><span>{{ item.movie.director }}</span>
      <br>
      <span class="text-info">Data produkcji: </span><span>{{ item.movie.publication_dates }}</span>
      <br>
      <span class="text-info">Ocena: </span><span class="badge badge-primary badge-pill">{{ item.movie_rating }}</span>
      <br>
      <span class="text-info">Liczba recenzji: </span><span>{{ item.number_of_reviews }}</span>
      <br>
      {% if item.movie_rating is null %}
      <span class="text-secondary">Napisz pierwszą recenzję.</span>
      <br>
      {% endif %}
      <a class="btn btn-primary btn-sm active" role="button" aria-pressed="true" href="/movies/{{ item.movie.id }}">Recenzje</a></li>
  </li>
  {% endfor %}
</ul>
{% endblock %}

critiflix/reviews/templates/search_results.html
{% extends 'base.html' %}
{% block title %}
    {% if form.is_valid and search_text %}
        Search Results for "{{ search_text }}"
    {% else %}
        Movie Search
    {% endif %}
{% endblock %}
{% block content %}
<style>
.light_text {
    font-family: "Noto Sans", sans-serif;
    color: white;
}
</style>
<h3 class="light_text">Wyniki wyszukiwania dla "<em>{{ search_text }}</em>"</h3>
<form class="light_text">
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Search</button>
</form>
<div style="margin-top: 40px;"></div>

<ul>
{% if form.is_valid and search_text %}
<ul class="list-group">
    {% for movie in movies %}
    <li class="list-group-item">
        <span class="text-info">Tytuł: </span> <a href="{% url 'movie_detail' movie.pk %}">{{ movie }}</a>
        <br/>
        <span class="text-info">Aktorzy: </span>
        {% for actor in movie.moviecast_set.all %}
        {{ actor.actor.first_names }} {{ actor.actor.last_names }}{% if not forloop.last %}, {% endif %}
        {% empty %}
        Brak aktorów
        {% endfor %}
    </li>
    {% empty %}
        <li class="list-group-item">Nie znaleziono wyników.</li>
    {% endfor %}
</ul>
</ul>
{% endif %}
{% endblock %}

critiflix/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Wymagane znaczniki meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>{% block title %}Critiflix{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap">    

  </head>
  <body>
        <nav class="navbar navbar-expand-sm navbar-dark sticky-top">
          <a class="navbar-brand" href="/">{% block brand %}<img src="{% static 'reviews/logo.png' %}"> {% endblock %}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/movies/">Baza filmów <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Wyloguj</a>
              </li>
            </ul>
            <form action="{% url 'movie_search' %}"class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search" value="{{ search_text }}" minlength="3">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Wyszukaj</button>
            </form>
          </div>
        </nav>
        {% block content %}
        <div class="home-page-container">
          <h1 class="noto-sans home-page-text">Twoje źródło inspiracji filmowej na Netflixie!</h1>
        </div>
        {% endblock %}


  <!-- Copyright -->
  <footer class="page-footer font-small black-footer">
    <div class="footer-copyright text-center py-3">
        © 2024 Copyright:
        <a href="https://github.com/Pawelpaprzycki"> Paweł Paprzycki</a>
        <p>Projekt: Paweł Paprzycki</p>
        <p>Kontakt: <a href="mailto:pawel.paprzycki94@gmail.com">pawel.paprzycki94@gmail.com</a></p>
    </div>
  </footer>

  <!-- Copyright -->
  </body>
</html>